App\Entity\Post:
  attributes:
    max_depth: 1
    id:
      groups: [ 'post_list', 'post_show' ]
    createdAt:
      groups: [ 'post_list', 'post_show' ]
    updatedAt:
      groups: [ 'post_list', 'post_show' ]
    author:
      groups: [ 'post_show' ]
    category:
      groups: [ 'post_show' ]
      max_depth: 1
    parameterValues:
      groups: [ 'post_show' ]
      max_depth: 1